{
 "title": "Recommend Traffic Dashboard ",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{path=\"/recommend\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{path=\"/recommend\",status=~\"5..\"}[5m])) / sum(rate(http_requests_total{path=\"/recommend\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency p50/95/99",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{path=\"/recommend\"}[5m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{path=\"/recommend\"}[5m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{path=\"/recommend\"}[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}