apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: recommender
  labels:
    app.kubernetes.io/name: recommender
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: recommender
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
